name: Daily TikTok Run

on:
  schedule:
    # 0 1 = 01:00 UTC
    - cron: '0 1 * * *'
  workflow_dispatch: # Enables manual trigger button

jobs:
  run-streak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps chromium

      - name: Run script
        env:
          TIKTOK_AUTH_JSON: ${{ secrets.TIKTOK_AUTH_JSON }}
        run: python tiktok.py
